import { TypographyVariantsOptions } from '@mui/material/styles/createTypography';

export const typography: TypographyVariantsOptions = {
  fontFamily: '"Open Sans Variable", "Helvetica", "Arial", "sans-serif"',
  headlineLarge: {
    fontSize: 32,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '40px',
    letterSpacing: 0,
  },
  headlineMedium: {
    fontSize: 28,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '36px',
    letterSpacing: 0,
  },
  headlineSmall: {
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '32px',
    letterSpacing: 0,
  },
  titleLarge: {
    fontSize: 22,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '28px',
    letterSpacing: 0,
  },
  titleMedium: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '24px',
    letterSpacing: 0.15,
  },
  titleSmall: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: 0.1,
  },
  bodyLarge: {
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '24px',
    letterSpacing: 0.5,
  },
  bodyMedium: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '20px',
    letterSpacing: 0.25,
  },
  bodySmall: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 400,
    lineHeight: '16px',
    letterSpacing: 0.4,
  },
  labelLarge: {
    fontSize: 14,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '20px',
    letterSpacing: 0.1,
  },
  labelMedium: {
    fontSize: 12,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.5,
  },
  labelSmall: {
    fontSize: 11,
    fontStyle: 'normal',
    fontWeight: 500,
    lineHeight: '16px',
    letterSpacing: 0.5,
  },
};
